### ISSUE TITLE
Chapter 10 has invalid YAML syntax

### ISSUE THREAD

**Issue by Nnemr** [sixeyed/diamol#71]
**Exercise**
10.4
**Problem**
The syntax for labels is incorrect. When you run `docker-compose -f ./docker-compose.yml -f ./docker-compose-prod.yml config`, the following error occurs:

```
parsing /mnt/d/projects/diamol/ch10/exercises/image-gallery/docker-compose-prod.yml: yaml: unmarshal errors:
  line 9: mapping key "x-labels" already defined at line 3
```
**Docker version**
Docker version 24.0.6, build ed223bc

**Code version**
```
commit 71384f8c09a8e0b3867a2c73ae09549774a21e85 (HEAD -> nnemr/update-ch10-exercise, origin/master, origin/HEAD, master)
Author: Elton Stoneman <elton@sixeyed.com>
Date:   Fri Mar 5 15:43:14 2021 +0000

    Bump Apache versions
```

**Comment by ChoiWheatley** [comment]
Since "x-labels" defined at line 3 and line 9, you can avoid duplicated keys:

```yaml
x-logging: &logging
  logging:
    options:
      max-size: '100m'
      max-file: '10'

x-labels: &labels
  app-name: image-gallery
```
